rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - bundle install
  - berks install
script:
  - bundle exec foodcritic -f any . --tags ~FC005
  - bundle exec rubocop
  - bundle exec rspec --color --format progress
